### PR TITLE
Move all txt files from data to data_static in complience with latest gmod security update

### PR DESCRIPTION
**Pull request by Marshall-vak**
The workshop version of jazztronauts will not be loaded in the latest version as there are text files in the data directory. As of the latest update all text files need to be located in data_static.

### CODE REVIEW

**Comment by WinterPhoenix** [comment]
This is incomplete. Usage of `file.Read` needs to be updated as well to use the new path.
- `file.Read("something.txt", "DATA")` -> `file.Read("data_static/something.txt", "GAME")`
- `file.Read("data/something.txt, "GAME")` -> `file.Read("data_static/something.txt", "GAME")`

**Comment by Marshall-vak** [comment]
My mistake I will rectify this as soon as I can.

**Comment by Foohy** [comment]
Hey hey, thanks for working on this. I did some investigation and it looks like the whitelist now also affects soundscape *.txts too, so on my machine I'm working on a (very small) reusable pipeline for packing them into our bsps. Additionally, I'm building this off the `workshop` branch so that we can hotfix the existing live version without pulling in whatever junk's currently on main.

I think that might run into trouble with this PR, but I'm hoping to be done with it in a few hours. I don't want you to throwaway your work, but for coordination's sake it might be easier if I merge my changes up to mainline instead of having two fixes doing the same thing.

**Comment by Marshall-vak** [comment]
Hey man all good you can close it if you would like. It does seem like they just blacklisted all .txt files that aren't in `data_static/`. I don't know how particles work so I didn't want to touch particles_manifest.txt and break something.

**Comment by Foohy** [comment]
Whew, okay, closing this because the hotfix has been applied in b2faa2dac8ee84dbf45b1fa86ba4b148ff43dded and merged with mainline in 9783ad1db80acae6fb098cbdb488f2e2b85baff0 
Thanks ya'll!!

**Pull request closed without merging**
