### PR TITLE
Green bar on completed missions

### PR DESCRIPTION
**Pull request by Commenter25**
Based off #45, pretty self explanatory. Improved the logic a bit to only use one if. Also removed a random empty unreferenced function.

### CODE REVIEW

**Review by SageJFox — CHANGES_REQUESTED** [review]
I think that `if perc > 0` check is still good, as that for sure prevents the bar from potentially drawing a single pixel-wide box on the side when someone has 0 of the required props.

**Comment by Commenter25** [comment]
I don't think that's mathematically possible. The width is calculated by multiplying by the percentage, and if the percentage is zero... well, it'll multiply by zero, which is nothing.

That said, just to be certain if it's a concern, I went ahead and re-added it.

**Comment by SageJFox** [comment]
Ha, haha. You think *actual* math has any bearing on 2D drawing. 

Seriously though, I don't know *for sure* that it's an issue in Source/GMod, but I do know it's been an issue on at least *some hardware* in every other game engine I've used. Better to just explicitly not draw it than leave it up to the renderer to understand that a 0 width means don't draw it.

**Review by SageJFox — APPROVED** [review]
oh hey you think it'd've told me about this, lul

**Pull request closed without merging**
