### PR TITLE
Make bus unremovable

### LINKED ISSUE #33: Remover tool usable on the bus
After unlocking the gmod spawnmenu, you can give yourself a toolgun and just use remove on the bus

### PR DESCRIPTION
**Pull request by Commenter25**
Closes #33 

If you use the spawnmenu to get a toolgun, and try using the remover tool on the bus, the bus will no longer be removed. Instead, you will drop your toolgun and be frozen for 1.5s as the screen shakes with an electric shock sound.

### CODE REVIEW

**Review by SageJFox — CHANGES_REQUESTED** [review]
At first I was worried that this seems a little mean, but then I remember what it is the person would be trying to do.

Just one small issue, should probably have an `if IsValid(ply)` check in the timer. If that person leaves the server while frozen, it'll throw a lua error without it.

**Comment by Commenter25** [comment]
Yeah, I feel like this is such a specific action to think of doing, and you'd have to play for a while to be able to even do it, so making the bus taze you is just kinda fun.

Good catch on the valid check, I wouldn't have thought of that. I mean, who would leave within that 1.5 second window...

**Comment by SageJFox** [comment]
It comes up a lot as weird outlier Lua errors, just gotten used to IsValid'ing everything in any timer longer than 0. x'd

**Review by SageJFox — APPROVED** [review]

**Comment by Foohy** [comment]
This is hilarious. Mergin' that in!

**Pull request merged**
