### PR TITLE
Add multiplayer conditional for dialogue

### LINKED ISSUE #98: [Suggestion] Single-player dialog changes?
I have noticed that the game still uses the plural when referring to the active party, even when there's only one person playing; would it be difficult to change it so it uses the singular if only one person is active on the server?

### PR DESCRIPTION
**Pull request by Commenter25**
Closes #98

I'm not sure if there's any other situations where the text specifically addresses multiple players. I think everything else in the intro is pretty neutral. But if anyone knows anything, I'll change it as well.

### CODE REVIEW

**Review by SageJFox — APPROVED** [review]
Looks good to me!

**Comment by SageJFox** [comment]
Maybe a bit of a "I bought this waffle press so I'm gonna get my money's worth out of it" scenario, but, in the intro, the Bartender has the line

> You'll want to fasten yourself securely in your seat, and brace yourself.

Could add a multiplayer check and add an alternate of

> You'll want to fasten yourselves securely in your seats, and brace yourselves.

**Comment by Commenter25** [comment]
Can't test it at the moment like I normally would, but this should be good! I also want to mention: yes, I absolutely fucking hate the whole added function just for an if check; but it seems Lua doesn't have a real ternary operator to make it compact, so I felt like squishing it into one line just kinda looks awful:

```lua
multiplayer = function() if player.GetCount() > 1 then return true else return false end end
```

**Comment by SageJFox** [comment]
Couldn't you do this?

`multiplayer = function() return player.GetCount() > 1 end`

Or is it too early for me to be thinking just yet. x'd

**Comment by Commenter25** [comment]
god why didnt i think of that, you're probably right. I remember trying `return player.GetCount() - 1`, and then I realized Lua doesn't consider 0 as false and I'm just JS-pilled xd

I'm still like, trying to hyperfocus on studying, but I can probably squeeze in testing that real quick later. Out of curiosity, do you know where the game save is stored, so I can back that up?

**Comment by SageJFox** [comment]
Y'know, your original attempt would technically be more accurate (since it'd make it "0 players" rather than "0 player", not that that should ever show up) You *could* just wrap your logic in an `isbool()`, that converts 0 to false and any other number to true.

As for the save data, that's stored in SQL, which will be sv.db and cl.db in your root folder, but keep in mind that those are shared with every addon. Why are you concerned with the save data for this?

**Comment by Foohy** [comment]
I think the other prologue PR #161  touched some of the same files as this and caused some conflicts, but I reviewed the change on its own and looks all good to me, very useful. I wouldn't want to make assumptions but fixing the conflicts, but I'll merge as soon as those are all ready 2 rumble

**Comment by Commenter25** [comment]
oh christ what did it do trying to fix the conflicts

i think im just going to reconstruct this in a new branch

**Pull request closed without merging**
