### PR TITLE
Prologue Polishing

### PR DESCRIPTION
**Pull request by Commenter25**
Depends on #158

I did a lot more here than I expected! I added more expressions, tightened up the timing, added more animations... I'm curious if I'll wind up revamping everything else anywhere near this much.

Here's the highlight changes that aren't just reorganizing the text itself or spelling/grammar related:

- Tweaked many animations to be timed more directly with the dialogue, such as the hand sweep on "floss their teeth with their spines"
- Made it so the Singer is more directly facing the Bartender when handing over the shard, then starts looking around (searching for a way out) rather than awkwardly staring at nothing for the next minute
- Made expressions reset more at the end of shots, rather than lingering
- Fixed mention of Portable Bus Stop's old gun model, changed to car keys
- Added actual animations+expressions to 1b
- Bartender is actually moving in the background of 3a rather than blankly staring at the shelves (including a sigh when the singer snaps, like a "here we go again")
- Kept Singer out of frame in 3a so you don't realize they're just kinda standing there doing nothing
- Tweaked the Singer's angle when they spot you, and added a funny little double-blink
- Moved out shot of the players to encompass the whole room (which could hypothetically be a whole lobby), and to make sure nobody's at the edge of the screen. It was very easy to jump right before the trigger, wind up right against the window, and have the camera pointing at the ground with a player stretched out on the edge
- Also moved shot at end of 3a, to show more of the room, from a higher angle, and have the wall that breaks more centered and easy to see, unlikely to be obstructed by players

Here's a video of how it looks now. I had to crunch the audio to fit the size limit without looking dreadful, so just, ignore that. I also encoded in h265, so you might have to download it to get it to play. 10MB is shockingly limiting...

https://github.com/Foohy/jazztronauts/assets/35016761/ad44599d-4d1c-491a-b9af-d2de747ef735

Feel free to ask for elaboration on any changes if needed!

### CODE REVIEW

**Comment by Commenter25** [comment]
In the morning I'll add an extra commit to this, utilizing the new setspeaker shorthand! For now, I must sleep, for it is nearly 11pm, which is the sleeping time of the letter C. So consider this unfinished until tomorrow!

**Comment by Commenter25** [comment]
Everything is done and I am satisfied now, ready for review!

**Comment by Commenter25** [comment]
My hopes were misplaced, now this is gonna conflict with SageJFox's PR, at bare minimum with the emote macros thing :sob:

**Comment by SageJFox** [comment]
A comparison video would help, yeah (or at least, an after video). It's hard to visualize what some of these changes are with just the diff. From what I can tell, most of them seem good, but there's a couple I'd have to see in action to be sure on.

Oh yeah, and I wouldn't worry too much about the macros thing, they're easy enough to find/replace. Though assuming we go with them, would probably un-shorthand setting the skins with the speaker so it's more readily apparent what emotion's being set.

**Comment by Commenter25** [comment]
I don't think I have time to throw together a more thorough side by side video like I hoped, I've gotta stop procrastinating and focus hard on life the next week, but I will at least get a recording of how it looks now and have that up today.

And yeah, I'm not too worried about switching everything over to the macro system, it just kinda leaves this in limbo. But I don't mind switching everything over when the time comes. And yeah, I'd undo the setspeaker shortcut as well.

**Comment by Commenter25** [comment]
Recording added! I've had Handbrake in the background doing trial and error all day, I hate file upload limits xd

**Review by SageJFox — APPROVED** [review]
Alright, thank you for the video. Looks good to me!

**Comment by Foohy** [comment]
Looking good from here as well, mergin' it in!

**Pull request merged**
