### PR TITLE
Added SWEP selection icons

### PR DESCRIPTION
**Pull request by Lixquid**
Adds some basic SWEP selection icons because the default SWEP selection icon is just 👎.

Icons are from [material design icons](https://github.com/google/material-design-icons).

Had to overload `DrawWeaponSelection` because the `weapon_base` one doesn't understand png materials.

Hopefully the assumption is someone that's considerably more sex at visual design can do better icons in the future??

### CODE REVIEW

**Comment by Foohy** [comment]
Oh my these help a lot, definite leagues better than nothing at all, thanks for doing that haha.

It all looks good, but dunno if there was a reason you `AddCSLuaFile("weapons/weapon_hack")` in weapon_hacker.lua. It nbd, I can fix it if you want after merging, just don't think it's doing anything.

**Comment by Lixquid** [comment]
Whoops, left that in there when I was thinking about adding the textures to the download list and I forgot about `resource.AddFile`

If we're assuming the textures will be in the content pack, feel free to go ahead and just remove it.

**Comment by Foohy** [comment]
Yep no problem, the textures will just be packed in with everything else. Thanks for this!

**Comment by xDShot** [comment]
Shouldn't be there already defined _DrawWeaponSelection_ method in weapon\_base? Why it doesn't inherit from?

**Pull request merged**
