### PR TITLE
Eject players in-bounds when leaving bus from void

### LINKED ISSUE #15: don't allow the player to leave the chair when they're in the bus and the bus is traveling

### PR DESCRIPTION
**Pull request by Commenter25**
Closes #15

- When the bus starts leaving a level, a hook is added for when a player tries to leave.
- It looks for a valid position behind the bus in intervals of 100 units; or until it has gone 2000 units away, since if nothing is within that it'll likely infinite loop and crash.
- Then it sets the player's speed really fast and kills them. It makes for a very punchy ragdoll! The killfeed considers it a suicide.
- It also skips the usual spectator system post-deathcam, and directly spawns the player in the bus, since spectating a point out of bounds is very jarring.

It's not a perfect solution, but it worked in most scenarios I tested, up and down, short and long, ejecting early or late. And when it does break, it shouldn't be as immersion breaking, since you still die rather than being trapped. The bus is kinda inherently janky anyway, so whatever!

### CODE REVIEW

**Review by SageJFox — CHANGES_REQUESTED** [review]
Would using the location of the bus's exit portal (stored in `self.ExitPortal` ) work better than the position searching loop?

**Comment by Commenter25** [comment]
The problem with that is, this is hooked right when the bus starts moving. I didn't figure out to run it only when the bus reaches the void. There probably is a way somewhere that I just didn't spot, and at that point, yeah it would probably be better.

**Comment by SageJFox** [comment]
That's fair. Should be fine as is.

**Review by SageJFox — APPROVED** [review]

**Comment by Foohy** [comment]
I love the good touch of setting the player's velocity so they ragdoll. Looks good to me!

**Pull request merged**
