### PR TITLE
Add stairs to pool in jazz_outro

### PR DESCRIPTION
**Pull request by Fighterbuilder**
The lack of pool stairs in jazz_outro was bothering me, so I copied over the ones from jazz_bar.
I didn't include a .bsp file because something wasn't set up properly when I compiled it myself and some of the dynamic props were missing, though I'm hoping it's just a compilation issue on my end. If someone who knows what they're doing could check the .vmf and verify that everything still works, I'd greatly appreciate it.

### CODE REVIEW

**Comment by SageJFox** [comment]
I plan to fix this issue with an update to the files that would make syncing changes to the bar with the outro much more streamlined.

**Comment by Fighterbuilder** [comment]
Ahh, ok.

**Comment by SageJFox** [comment]
Unfortunately my attempts to get instances (or manifests) for the bar maps working in a reasonable fashion didn't pan out.

The next attempt for this would be to restructure in a way that the outro maps (as jazz_outro2 also has similar old-setup problems) aren't actually separate from jazz_bar. This would also help with custom hubs, as they'd be all contained in the one map as well.

Of course, this'll be a big change to things, and I can't promise that it's actually even possible (though, best I can tell, it *should* be). Ideally, we get some restructuring to how scenes are set up done first, as that'd make positioning all the elements much easier.

**Comment by Fighterbuilder** [comment]
Yeah, that probably sounds like it'd be a better idea in the long run. Would this possibly work as a stopgap solution though?

**Comment by SageJFox** [comment]
Looking more closely, it seems we *might* have a more up-to-date version of the outro in the currently compiled version than we do in the vmf (we had a similar problem with jazz_bar itself, but that was taken care of already). I'd rather not compile over that file, just in case something from it turns out to be important.

**Comment by Fighterbuilder** [comment]
Ohhhh ok. I wasn't aware of that!

**Review by SageJFox — APPROVED** [review]
Took another look, should be fine.

**Comment by Foohy** [comment]
Yep, solid change that'll be great for now. Thank you tons!

**Pull request merged**
